image: selenium/standalone-chrome:105.0
stages:
  - test
test:
  stage: test
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - .gradle
  script: sudo ./gradlew clean test --tests "runners.TestRunner" -Denv=ci-calidris --stacktrace --info